Capstone/Capstone/Models/hospital.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hospital
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hospital()
        {
            this.responses = new HashSet<respons>();
            this.users = new HashSet<user>();
            this.questions = new HashSet<question>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool active { get; set; }
        public System.DateTime created_on { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<respons> responses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<question> questions { get; set; }
    }
}

Capstone/Capstone/Controllers/MaintenanceController.cs
using Capstone.Models;
using log4net;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Capstone.Controllers
{
    [Authorize]
    public class MaintenanceController : Controller
    {
        private static ILog log = log4net.LogManager.GetLogger(typeof(MaintenanceController));
        // GET: Maintenance
        public ActionResult Hospitals()
        {
            //using (MedicalEntities db = new MedicalEntities())
            //{
            //    LOV_Type_Ref list = (from l in db.LOV_Type_Ref
            //                         where l.ID == (LOV_Type_Ref_type?)LOV_Type_key
            //                         select l).FirstOrDefault();

            //    return View(list ?? new LOV_Type_Ref());
            //}
            return View();
        }
        public JsonResult GetHospitalListJSON()
        {
            using (MedicalEntities db = new MedicalEntities())
            {
                db.Configuration.LazyLoadingEnabled = false;
                var list = (from l in db.hospitals
                            select l).ToList();

                return Json(list, JsonRequestBehavior.AllowGet);
            }
        }

        public static IEnumerable<hospital> GetHospitalList()
        {
            IEnumerable<hospital> ReturnList;

            using (MedicalEntities db = new MedicalEntities())
            {
                ReturnList = db.hospitals.Where(x=>x.active == true).OrderBy(x=>x.name).ToList();
            }

            return ReturnList;
        }

        class HospitalInput
        {
            public int id { get; set; }
            public string name { get; set; }
            public bool active { get; set; }
            public System.DateTime created_on { get; set; }
        }
        public JsonResult UpdateHospital_List(string lines)
        {
            try
            {
                var ListOfHospitals = JsonConvert.DeserializeObject<List<HospitalInput>>(lines);
                using (MedicalEntities db = new MedicalEntities())
                {
                    foreach (HospitalInput HospitalValues in ListOfHospitals)
                    {

                        if (!(db.hospitals.Any(t => t.id == HospitalValues.id)))
                        {
                            //add new hospital
                            hospital NewHospital = new hospital();

                            NewHospital.name = HospitalValues.name;
                            NewHospital.active = HospitalValues.active;
                            NewHospital.created_on = DateTime.Now;
                            db.hospitals.Add(NewHospital);

                        }
                        else
                        {
                            hospital existingHospital = db.hospitals.Where(t => t.id == HospitalValues.id).FirstOrDefault();
                            bool SomethingChanged = false;

                            if (existingHospital.name != HospitalValues.name || existingHospital.active != HospitalValues.active)
                                SomethingChanged = true;

                            existingHospital.name = HospitalValues.name;
                            existingHospital.active = HospitalValues.active;

                            if (SomethingChanged)
                                db.Entry(existingHospital).State = System.Data.Entity.EntityState.Modified;
                        }
                    }

                    db.SaveChanges();
                }
                return Json(new { });
            }
            catch (Exception e)
            {
                log.Error(e);
                log.Error(lines);
                throw e;
            }
        }

        public ActionResult HospitalQuestions(int HospitalID)
        {
            using (MedicalEntities db = new MedicalEntities())
            {
                hospital thisHospital = db.hospitals.Where(x => x.id == HospitalID).FirstOrDefault();
                if (thisHospital == null || thisHospital.id == 0)
                    return RedirectToAction("hospital");
                return View(thisHospital);
            }
        }
        public JsonResult GetHospitalQuestionsList(int HospitalID)
        {
            using (MedicalEntities db = new MedicalEntities())
            {
                db.Configuration.LazyLoadingEnabled = false;
                var list = db.questions.Where(x => x.hospital_id == HospitalID).ToList();

                return Json(list, JsonRequestBehavior.AllowGet);
            }
        }

        class HospitalQuestionsInput
        {
            public int id { get; set; }
            public string text { get; set; }
            public bool active { get; set; }
            public bool multiple_choice { get; set; }
            public System.DateTime created_on { get; set; }
        }
        public JsonResult UpdateHospitalQuestions_List(int HospitalID, string lines)
        {
            try
            {
                var ListOfHospitalQuestions = JsonConvert.DeserializeObject<List<HospitalQuestionsInput>>(lines);
                using (MedicalEntities db = new MedicalEntities())
                {
                    foreach (HospitalQuestionsInput HospitalQuestionValues in ListOfHospitalQuestions)
                    {

                        if (!(db.questions.Any(t => t.id == HospitalQuestionValues.id)))
                        {
                            //add new question
                            question NewQuestion = new question();

                            NewQuestion.text = HospitalQuestionValues.text;
                            NewQuestion.active = HospitalQuestionValues.active;
                            NewQuestion.created_on = DateTime.Now;
                            NewQuestion.hospital_id = HospitalID;
                            NewQuestion.user_id = System.Web.HttpContext.Current.User.Identity.GetUserId();
                            NewQuestion.free_text_field = false;
                            NewQuestion.multiple_choice = true;

                            db.questions.Add(NewQuestion);

                        }
                        else
                        {
                            question existingHospitalQuestion = db.questions.Where(t => t.id == HospitalQuestionValues.id).FirstOrDefault();
                            existingHospitalQuestion.free_text_field = false;
                            existingHospitalQuestion.multiple_choice = true;
                            

                            existingHospitalQuestion.text = HospitalQuestionValues.text;
                            existingHospitalQuestion.active = HospitalQuestionValues.active;

                            db.Entry(existingHospitalQuestion).State = System.Data.Entity.EntityState.Modified;
                        }
                    }

                    db.SaveChanges();
                }
                return Json(new { });
            }
            catch (Exception e)
            {
                log.Error(e);
                log.Error(lines);
                throw e;
            }
        }
        public ActionResult HospitalQuestionOptions(int QuestionID)
        {
            using (MedicalEntities db = new MedicalEntities())
            {
                question thisQuestion = db.questions.Where(x => x.id == QuestionID).FirstOrDefault();
                if (thisQuestion == null || thisQuestion.id == 0)
                    return RedirectToAction("hospital");
                return View(thisQuestion);
            }
        }
        public JsonResult GetHospitalQuestionOptionsList(int QuestionID)
        {
            using (MedicalEntities db = new MedicalEntities())
            {
                db.Configuration.LazyLoadingEnabled = false;
                var list = db.options.Where(x => x.question_id == QuestionID).ToList();

                return Json(list, JsonRequestBehavior.AllowGet);
            }
        }

        class HospitalQuestionOptionsInput
        {
            public int id { get; set; }
            public string text { get; set; }
            public bool active { get; set; }
            public System.DateTime created_on { get; set; }
        }
        public JsonResult UpdateHospitalQuestionOptions_List(int QuestionID, string lines)
        {
            try
            {
                var ListOfHospitalQuestionOptions = JsonConvert.DeserializeObject<List<HospitalQuestionOptionsInput>>(lines);
                using (MedicalEntities db = new MedicalEntities())
                {
                    foreach (HospitalQuestionOptionsInput HospitalQuestionOptionValues in ListOfHospitalQuestionOptions)
                    {

                        if (!(db.options.Any(t => t.id == HospitalQuestionOptionValues.id)))
                        {
                            //add new hospital
                            option NewHospitalquestionOption = new option();

                            NewHospitalquestionOption.text = HospitalQuestionOptionValues.text;
                            NewHospitalquestionOption.active = HospitalQuestionOptionValues.active;
                            NewHospitalquestionOption.created_on = DateTime.Now;
                            NewHospitalquestionOption.question_id = QuestionID;
                            db.options.Add(NewHospitalquestionOption);

                        }
                        else
                        {
                            option existingHospitalQuestionOption = db.options.Where(t => t.id == HospitalQuestionOptionValues.id).FirstOrDefault();
                            bool SomethingChanged = false;

Capstone/Capstone/Views/Maintenance/HospitalQuestionOptions.cshtml
@model Capstone.Models.question
@using Newtonsoft.Json

@{
    ViewBag.Title = "Capstone Medical - Hospitals";

}

<html>
<head>
    <title>Hospital Question Options Maintenance</title>

    <link rel="stylesheet" href="~/Content/tabulator.min.css">
    <script type="text/javascript" src="~/Scripts/jquery-ui.js"></script>
    <script type="text/javascript" src="~/Scripts/tabulator.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery_wrapper.min.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {

            var DateFormatter = function (cell, formatterParams) { //plain text value
				if ((cell.getValue() == null) || (cell.getValue() == "/Date(-62135575200000)/"))
					return "";
                var x = Date(parseInt(cell.getValue().replace('/Date(', '')));
                return new Date(parseInt(cell.getValue().replace('/Date(', ''))).toLocaleDateString();
            };

            $("#ValuesTable").tabulator({
                ajaxURL: "../Maintenance/GetHospitalQuestionOptionsList", //ajax URL
                ajaxParams:{QuestionID:"@Model.id"},
                ajaxConfig: "POST", //ajax HTTP request type
                layout: "fitColumns",
                tooltips: true,
                addRowPos: "top",
                history: true,
                pagination: "local",
                paginationSize: 25,
                movableColumns: true,
                resizableRows: true,
                initialSort: [
                    { column: "text", dir: "asc" },
                ],
                columns: [
                    { title: "id", field: "id", visible: false },
                    { title: "Text", field: "text", editor: "input", editable: true },
                    { title: "Active", field: "active", align: "center", editor: true, formatter: "tickCross" },
                    { title: "Created_On", field: "created_on", editor: "input", editable: false, align: "center", formatter: DateFormatter}
                ]
            });

        });

        function AddValueRow() {
            $("#ValuesTable").tabulator("addRow", {});
        }

        function SaveValues(TabulatorDivID) {
            ShowSpinnerSaving();
            var ArrayObjectRawJSONed = CreateJSONArrayObjectFromTabulator(TabulatorDivID);
            $.ajax({

                url: "../Maintenance/UpdateHospitalQuestionOptions_List",
                data: { QuestionID:"@Model.id", lines: ArrayObjectRawJSONed },
                type: 'Post',
                dataType: 'json',
                success: function (results) {
                    HideSpinner();
                    $("#ValuesTable").tabulator("setData");
                },

                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    HideSpinner();
                    alert("Status: " + textStatus); alert("Error: " + errorThrown)
                }
            });
        }
        function CreateJSONArrayObjectFromTabulator(TabulatorDivID) {

            var arrayobject = new Array();
            var arrayobjectRaw = new Array();

            if (TabulatorDivID === undefined)
                return arrayobject
            var TabulatorData = $(TabulatorDivID).tabulator("getData");
            TabulatorData.forEach(function (row) {
                if (row != undefined) { arrayobjectRaw.push(row); }
            });
            return JSON.stringify(arrayobjectRaw);
        };

    </script>

</head>
<body>

    <h3>Hospital: @Capstone.Controllers.MaintenanceController.GetHospitalName(Model.hospital_id)</h3>
    <h3>Question: @Model.text</h3>
    <h3>Options:</h3>
    <br />
    <input id="AddValue" type="submit" value="Add Row" class="Branded" onclick="AddValueRow()" style="margin-right:20px;" />
    <input id="AddValue" class="Branded" type="submit" value="Save Values" onclick="SaveValues('#ValuesTable')" />
    <br />
    <br />
    <div id="ValuesTable"></div>




    <div id="saving">
        <div id="savingcontent">
            <p id="savingspinner">
                Saving...
            </p>
        </div>
    </div>
</body>
</html>

Capstone/Capstone/Views/Maintenance/HospitalQuestions.cshtml
@model Capstone.Models.hospital
@using Newtonsoft.Json

@{
    ViewBag.Title = "Capstone Medical - Hospitals";

}

<html>
<head>
    <title>Hospital Questions Maintenance</title>

    <link rel="stylesheet" href="~/Content/tabulator.min.css">
    <script type="text/javascript" src="~/Scripts/jquery-ui.js"></script>
    <script type="text/javascript" src="~/Scripts/tabulator.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery_wrapper.min.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {

            var DateFormatter = function (cell, formatterParams) { //plain text value
				if ((cell.getValue() == null) || (cell.getValue() == "/Date(-62135575200000)/"))
					return "";
                var x = Date(parseInt(cell.getValue().replace('/Date(', '')));
                return new Date(parseInt(cell.getValue().replace('/Date(', ''))).toLocaleDateString();
            };

            $("#ValuesTable").tabulator({
                ajaxURL: "../Maintenance/GetHospitalQuestionsList", //ajax URL
                ajaxParams:{HospitalID:"@Model.id"},
                ajaxConfig: "POST", //ajax HTTP request type
                layout: "fitColumns",
                tooltips: true,
                addRowPos: "top",
                history: true,
                pagination: "local",
                paginationSize: 25,
                movableColumns: true,
                resizableRows: true,
                initialSort: [
                    { column: "name", dir: "asc" },
                ],
                columns: [
                    { title: "id", field: "id", visible: false },
                    { title: "Text", field: "text", editor: "input", editable: true },
                    { title: "Multiple Choice Options", field: "id", align: "center", editor: false, formatter:"link", formatterParams:{
                        label:"Maintain Options",
                        urlPrefix:"@Url.Action("HospitalQuestionOptions", "Maintenance")?QuestionID=",
                        } },
                    { title: "Active", field: "active", align: "center", editor: true, formatter: "tickCross" },
                    { title: "Created_On", field: "created_on", editor: "input", editable: false, align: "center", formatter: DateFormatter}
                ]
            });

        });

        function AddValueRow() {
            $("#ValuesTable").tabulator("addRow", {});
        }

        function SaveValues(TabulatorDivID) {
            ShowSpinnerSaving();
            var ArrayObjectRawJSONed = CreateJSONArrayObjectFromTabulator(TabulatorDivID);
            $.ajax({

                url: "../Maintenance/UpdateHospitalQuestions_List",
                data: { HospitalID:"@Model.id", lines: ArrayObjectRawJSONed },
                type: 'Post',
                dataType: 'json',
                success: function (results) {
                    HideSpinner();
                    $("#ValuesTable").tabulator("setData");
                },

                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    HideSpinner();
                    alert("Status: " + textStatus); alert("Error: " + errorThrown)
                }
            });
        }
        function CreateJSONArrayObjectFromTabulator(TabulatorDivID) {

            var arrayobject = new Array();
            var arrayobjectRaw = new Array();

            if (TabulatorDivID === undefined)
                return arrayobject
            var TabulatorData = $(TabulatorDivID).tabulator("getData");
            TabulatorData.forEach(function (row) {
                if (row != undefined) { arrayobjectRaw.push(row); }
            });
            return JSON.stringify(arrayobjectRaw);
        };

    </script>

</head>
<body>

    <h3>Hospital: @Model.name</h3>
    <h3>Questions: </h3>
    <br />
    <input id="AddValue" type="submit" value="Add Row" class="Branded" onclick="AddValueRow()" style="margin-right:20px;" />
    <input id="AddValue" class="Branded" type="submit" value="Save Values" onclick="SaveValues('#ValuesTable')" />
    <br />
    <br />
    <div id="ValuesTable"></div>




    <div id="saving">
        <div id="savingcontent">
            <p id="savingspinner">
                Saving...
            </p>
        </div>
    </div>
    <div id="HiddenQuestionTypeSelect" hidden>
        <select id="HiddenQuestionList">
            <option value="FreeText">Free Text</option>
            <option value="MultipleChoice">Multiple Choice</option>
        </select>
    </div>
</body>
</html>

Capstone/Capstone/Views/Maintenance/Hospitals.cshtml
@model Capstone.Models.hospital
@using Newtonsoft.Json

@{
    ViewBag.Title = "Capstone Medical - Hospitals";

}

<html>
<head>
    <title>Hospitals Maintenance</title>

    <link rel="stylesheet" href="~/Content/tabulator.min.css">
    <script type="text/javascript" src="~/Scripts/jquery-ui.js"></script>
    <script type="text/javascript" src="~/Scripts/tabulator.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery_wrapper.min.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {

            var DateFormatter = function (cell, formatterParams) { //plain text value
				if ((cell.getValue() == null) || (cell.getValue() == "/Date(-62135575200000)/"))
					return "";
                var x = Date(parseInt(cell.getValue().replace('/Date(', '')));
                return new Date(parseInt(cell.getValue().replace('/Date(', ''))).toLocaleDateString();
            };

            $("#ValuesTable").tabulator({
                ajaxURL: "../Maintenance/GetHospitalListJSON", //ajax URL
                ajaxConfig: "POST", //ajax HTTP request type
                layout: "fitColumns",
                tooltips: true,
                addRowPos: "top",
                history: true,
                pagination: "local",
                paginationSize: 25,
                movableColumns: true,
                resizableRows: true,
                initialSort: [
                    { column: "name", dir: "asc" },
                ],
                columns: [
                    { title: "id", field: "id", visible: false },
                    { title: "Name", field: "name", sorter:"string", editor: "input" },
                    { title: "Active", field: "active", align: "center", editor: true, formatter: "tickCross" },
                    { title: "Questions", field: "id", align: "center", editor: false, formatter:"link", formatterParams:{
                        label:"Hospital Questions",
                        urlPrefix:"@Url.Action("HospitalQuestions", "Maintenance")?HospitalID=",
                        } },
                    { title: "Created_On", field: "created_on", editor: "input", editable: false, align: "center", formatter: DateFormatter}
                ]
            });

        });

        function AddValueRow() {
            $("#ValuesTable").tabulator("addRow", {});
        }

        function SaveValues(TabulatorDivID) {
            ShowSpinnerSaving();
            var ArrayObjectRawJSONed = CreateJSONArrayObjectFromTabulator(TabulatorDivID);
            $.ajax({

                url: "../Maintenance/UpdateHospital_List",
                data: { lines: ArrayObjectRawJSONed },
                type: 'Post',
                dataType: 'json',
                success: function (results) {
                    HideSpinner();
                    $("#ValuesTable").tabulator("setData");
                },

                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    HideSpinner();
                    alert("Status: " + textStatus); alert("Error: " + errorThrown)
                }
            });
        }
        function CreateJSONArrayObjectFromTabulator(TabulatorDivID) {

            var arrayobject = new Array();
            var arrayobjectRaw = new Array();

            if (TabulatorDivID === undefined)
                return arrayobject
            var TabulatorData = $(TabulatorDivID).tabulator("getData");
            TabulatorData.forEach(function (row) {
                if (row != undefined) { arrayobjectRaw.push(row); }
            });
            return JSON.stringify(arrayobjectRaw);
        };

    </script>

</head>
<body>

    <h3>Hospitals: </h3>
    <br />
    <input id="AddValue" type="submit" value="Add Row" class="Branded" onclick="AddValueRow()" style="margin-right:20px;" />
    <input id="AddValue" class="Branded" type="submit" value="Save Values" onclick="SaveValues('#ValuesTable')" />
    <br />
    <br />
    <div id="ValuesTable"></div>




    <div id="saving">
        <div id="savingcontent">
            <p id="savingspinner">
                Saving...
            </p>
        </div>
    </div>

</body>
</html>